### ISSUE TITLE
Please change solid-js version in peerDependencies 

### ISSUE THREAD

**Issue by dolgof** [elite174/solid-resizable-panels#15]
I got an error when I was installing the package:

> npm ERR! Found: solid-js@1.8.16
> npm ERR! node_modules/solid-js
> npm ERR!   solid-js@"^1.8.16" from the root project
> 
> npm ERR! Could not resolve dependency:
> npm ERR! peer solid-js@"1.7" from solid-resizable-panels@0.5.3

Here it is:
`
  "peerDependencies": {
    "solid-js": "1.7"
  },
`

**Comment by elite174** [comment]
done in 0.5.4
