### ISSUE TITLE
Is there a plan for moving panel around ?

### ISSUE THREAD

**Issue by carere** [elite174/solid-resizable-panels#16]
Hello,

First of all, thx a lot for your lib !!! You just made my month ❤️ ❤️ 

I'm building an app with your solution integrated with Solid-UI (Shadcn/ui but for solidjs), and it works great !!!
I was wondering if you plan on adding the possibility to move panel around ? Like in [React Mosaic](https://nomcopter.github.io/react-mosaic/)
The goal is to be able to create a tiling window manager with SolidJS 😄

I'm not well versed with your code. Never did lot of Drag & drop stuff in frontend, but if you need some help, let me know, I'll be happy to help you build this amazing piece of technology 😃

Have a great day !!!

**Comment by elite174** [comment]
Hey!
This library is mostly about managing 2d-layouts, so I guess, this won't be supported in this library.
Funny though that I worked on solid-grid lib, but then I abandoned it 😆

**Comment by carere** [comment]
I'll try to implement drag & drop a panel in another group like with react mosaic, I got some idea about how to do it 😁
