### ISSUE TITLE
Not a issue but a suggesion.

### ISSUE THREAD

**Issue by BipanKishore** [elite174/solid-resizable-panels#18]
Would you like to work together. I'm building the mono repo for resizable-panels.
You can integrate your repo into and use the resizable-core also.
A common repo can increase our hit count :) .

https://github.com/BipanKishore/resizable-panes

If you liked it do give it a star and do check the demo.

**Comment by elite174** [comment]
I guess you don't need that
https://corvu.dev/docs/primitives/resizable/
these guys used my code and integrated it into this library.

**Comment by BipanKishore** [comment]
ok
